services:
  listsync-core:
    build:
      context: .
      dockerfile: Dockerfile.core
    container_name: listsync-core
    environment:
      # Timezone - Supports: IANA names (Europe/Paris), abbreviations (CET), offsets (UTC+1, GMT-5)
      - TZ=${TZ:-UTC}
      
      # Overseerr Configuration
      - OVERSEERR_URL=${OVERSEERR_URL}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY}
      - OVERSEERR_USER_ID=${OVERSEERR_USER_ID:-1}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-24}
      - AUTOMATED_MODE=true
      - OVERSEERR_4K=${OVERSEERR_4K:-false}
      
      # List Configuration (comma-separated)
      - IMDB_LISTS=${IMDB_LISTS}
      - TRAKT_LISTS=${TRAKT_LISTS}
      - LETTERBOXD_LISTS=${LETTERBOXD_LISTS}
      - MDBLIST_LISTS=${MDBLIST_LISTS}
      - STEVENLU_LISTS=${STEVENLU_LISTS}
      - TRAKT_SPECIAL_LISTS=${TRAKT_SPECIAL_LISTS}
      - TRAKT_SPECIAL_ITEMS_LIMIT=${TRAKT_SPECIAL_ITEMS_LIMIT}
      
      # Trakt API Configuration
      - TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}

      # Optional Discord webhook 
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      
      # Docker-specific settings
      - RUNNING_IN_DOCKER=true
      - NO_SANDBOX=1
      - DISPLAY=:99
    volumes:
      # Persist data directory
      - ./data:/usr/src/app/data
      # Mount environment file
      - ./.env:/usr/src/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python -m list_sync"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Note: Core-only ListSync deployment
    # - Only the core sync service (python -m list_sync)  
    # - No web UI or API server
    # - Minimal resource footprint
    # - Perfect for headless deployments 